package by.karpov.entity;

public enum Specialty {

    THERAPIST,
    CARDIOLOGIST,
    HEMATOLOGIST,
    SURGEON,
    GYNECOLOGIST,
    ONCOLOGIST,
    TRAUMATOLOGIST,
    UROLOGIST,
    OPHTHALMOLOGIST,
    OTOLARYNGOLOGIST,
    NEUROLOGIST,
    PSYCHIATRIST_NARCOLOGIST,
    PSYCHOTHERAPIST,
    ULTRASOUND_DOCTOR,
    FUNCTIONAL_DIAGNOSTIC_DOCTOR,
    RADIOLOGIST,
    REHABILITATION,
    DERMATOVENEROLOGIST
}
